version: '3'

services:
  frontend:
    image: nginx:stable-alpine
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-rtr.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend-svc.loadbalancer.server.port=80"
  
  backend:
    build: ./backend
    restart: always
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-rtr.rule=PathPrefix(`/api`)"
      - "traefik.http.services.backend-svc.loadbalancer.server.port=80"

  yxorp: 
    image: traefik
    restart: always
    command: 
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  